config/routes.rb
Rails.application.routes.draw do
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { registrations: 'registrations' }

  root 'welcomes#index'

  get '/dashboard', to: 'welcomes#dashboard'
  get '/users/:id', to: 'users#profile', as: 'profile'
  
  resources :jobs do
    resources :bids, shallow: true
  end
end

app/models/bid.rb
class Bid < ActiveRecord::Base

  belongs_to :job
  has_one :poster, through: :job
  belongs_to :applicant, :class_name => 'User', :foreign_key => 'applicant_id'

  accepts_nested_attributes_for :job

  validates :applicant, presence: true

  def self.initialize_new(bid, params, user)
    bid.job_id = params[:job_id]
    bid.note = params[:bid][:bid][:note]
    bid.applicant_id = user
    bid.save
  end

end

app/controllers/bids_controller.rb
class BidsController < ApplicationController

  before_action :authenticate_user!
  authorize_resource

  def index
    redirect_to dashboard_path
  end

  def show
    @bid = Bid.find(params[:id])
    @job = Job.find(@bid.job_id)
  end

  def new
    @job = Job.find(params[:job_id])
    @bid = @job.bids.new
    @bid.date_time = @job.date_time
  end

  def create
    @bid = Bid.create(bid_params)
    Bid.initialize_new(@bid, params, current_user.id)
    redirect_to jobs_path
  end

  def edit
    @bid = Bid.find(params[:id])
  end

  def update
    @bid = Bid.find(params[:id])
    @bid.update(bid_params)
    redirect_to dashboard_path
  end

  def destroy
    Bid.find(params[:id]).destroy
    redirect_to dashboard_path
  end

  private
  def bid_params
    params.require(:bid).permit(:job_id, :applicant_id, :date_time, :note)
  end

end

app/helpers/bids_helper.rb
module BidsHelper
end

app/views/bids/_form.html.haml
= form_for [@job, @bid] do |f|
  = f.fields_for :bid do |b| 
    .field
      = f.label :date_time
      = f.datetime_select  :date_time
    .field
      = b.label :note
      = b.text_field :note
  .actions
    = f.submit

app/views/bids/edit.html.haml
.form
  %h2 Edit Bid
  = render 'form'
  .page-nav
    = link_to 'CANCEL', dashboard_path
    = link_to 'DELETE', bid_path(@bid), method: :delete

app/views/bids/new.html.haml
.form
  %h2 Submit Offer
  = render 'form'
  .page-nav
    = link_to 'CANCEL', job_bids_path

app/views/bids/show.html.haml
.bid-show
  %h2= link_to @job.title, job_path(@job)
  %h4= @bid.date_time.to_formatted_s(:long_ordinal)
  %h3 Description
  %p= @job.description
  %h3 Helpr's Note
  %p= @bid.note
  - if @bid.applicant_id == current_user.id
    .page-nav
      = link_to 'EDIT', edit_bid_path(@bid)
      = link_to 'DELETE', bid_path(@bid), method: :delete