config/routes.rb
Rails.application.routes.draw do
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { registrations: 'registrations' }

  root 'welcomes#index'

  get '/dashboard', to: 'welcomes#dashboard'
  get '/users/:id', to: 'users#profile', as: 'profile'
  
  resources :jobs do
    resources :bids, shallow: true
  end
end

app/models/job.rb
class Job < ActiveRecord::Base

  has_many :bids
  has_many :applicants, through: :bids

  belongs_to :poster, :class_name => 'User', :foreign_key => 'poster_id'
  belongs_to :helper, :class_name => 'User', :foreign_key => 'helper_id'

  validates :poster, presence: true
  validates :description, presence: true
  validates :instructions, presence: true
  validates :date_time, presence: true
  validates :address, presence: true
  validates :postcode, presence: true

  def self.assign_user(job, user)
    job.poster_id = user
    job.save
  end

  def helper_assigned_email
    if helper
      UserMailer.job_allocation(helper, self).deliver
    end
  end

  def helper_status_json_object
    data = {}
    helper = self.helper
    applicants = self.applicants
    if helper.nil? && applicants == []
      return data = false
    elsif helper.nil?
      data['applicants'] = true
      self.bids.each do |bid|
        data[bid] = {
          applicant_name: bid.applicant.username,
          applicant_image: bid.applicant.image,
          applicant_id: bid.applicant.id,
          offer_time: bid.date_time.to_formatted_s(:long_ordinal),
          datetime: bid.date_time,
          note: bid.note,
        }
      end
    elsif
      data['helper'] = true
      helper = self.helper
      winning_bid = self.bids.where(applicant: helper)
      data['helper_name'] = helper.username
      data['helper_image'] = helper.image
      data['helper_id'] = helper.id
    end
    data.to_json
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]
  authorize_resource

  def index
    @jobs = Job.where('date_time > ?', Time.now).where( helper: nil )
    respond_to do |format|
      format.html
      format.json { render json: @jobs }
    end
  end

  def show
    @job = Job.find(params[:id])
    @data = @job.helper_status_json_object
    respond_to do |format|
      format.html
      format.json { render json: @data }
    end
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.create(job_params)
    Job.assign_user(@job, current_user.id)
    redirect_to jobs_path
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    @job.update(job_params)
    if @job.helper != nil
      @job.helper_assigned_email
    end
    respond_to do |format|
      format.html {redirect_to dashboard_path}
      format.json { head :no_content, status: :ok }
    end
  end

  def destroy
    Job.find(params[:id]).destroy
    redirect_to jobs_path
  end

  private
  def job_params
    params.require(:job).permit(:poster_id, :title, :description, :address, :date_time, :postcode, :instructions, :helper_id)
  end
  
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.haml
= form_for @job do |f|
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_field  :description
  .field
    = f.label :instructions
    = f.text_field  :instructions
  .field
    = f.label :address
    = f.text_field  :address
  .field
    = f.label :postcode
    = f.text_field  :postcode
  .field
    = f.label :date_time, 'Date & Time'
    = f.datetime_select  :date_time
  .actions
    = f.submit

app/views/jobs/edit.html.haml
.form
  %h2 Edit Job
  = render 'form'
  .page-nav
    = link_to 'CANCEL', jobs_path
    = link_to 'DELETE', job_path(@job), method: :delete

app/views/jobs/index.html.haml
.center-on
.jobs-index-map-container
  #jobs-index-map

.jobs-index-list
  .job-index-list-top
    %h2 Search
    %p
      %em
        See the jobs
        %span.jobs-index-filter#by-location near you,
        -# find the ones
        -# %span.jobs-index-filter#no-offers without offers yet,
        or enter a location below.
    %input#jobs-index-map-search{autofocus: true}
  - @jobs.each do |job|
    .job-index-post
      %h3= link_to job.title, job_path(job)
      %h4= job.date_time.to_formatted_s(:long_ordinal)
      %p= job.description

app/views/jobs/new.html.haml
.form
  %h3 Post Job
  = render 'form'
  .page-nav
    = link_to 'CANCEL', jobs_path

app/views/jobs/show.html.haml
#job-show-map
.address= @job.postcode
.job-id= @job.id

.standard-width-content
  .job-show-header
    %h2= @job.title
    %h4
      Posted by
      = link_to @job.poster.username, profile_path(@job.poster)
    
    - if user_signed_in?
      .bid-status
        - if @job.poster == current_user
          = link_to 'EDIT', edit_job_path
        - elsif @job.helper == current_user
          = link_to 'YOU HAVE WON', dashboard_path
        - elsif @job.applicants.include? current_user
          = link_to 'YOU HAVE OFFERED', dashboard_path
        - else
          = link_to 'I CAN HELP', new_job_bid_path(@job)
    - else
      .bid-status= link_to 'I CAN HELP', new_job_bid_path(@job)

  .job-show-content
    %h3 Description
    %p= @job.description
    - if @job.helper == nil
      %h3 Requested Time
      %p= @job.date_time.to_formatted_s(:long_ordinal)
    - if user_signed_in?
      - if @job.poster == current_user || @job.helper == current_user
        %h3 Instructions
        %p= @job.instructions
        %h3 Address
        %p= @job.address
        - if @job.helper
          %h3 Agreed time
          %p= @job.date_time.to_formatted_s(:long_ordinal)

  - if user_signed_in? && @job.poster == current_user
    .job-show-helper
      %h6 There are no offers to show yet.