config/routes.rb
Rails.application.routes.draw do
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { registrations: 'registrations' }

  root 'welcomes#index'

  get '/dashboard', to: 'welcomes#dashboard'
  get '/users/:id', to: 'users#profile', as: 'profile'
  
  resources :jobs do
    resources :bids, shallow: true
  end
end

app/models/welcome.rb
class Welcome < ActiveRecord::Base
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController

  before_action :authenticate_user!, except: [:index]
  authorize_resource

  def index
  end

  def dashboard
    @poster_jobs = current_user.poster_jobs.where('date_time > ?', Time.now)
    @helper_jobs = current_user.helper_jobs.where(['date_time > ?', Time.now])
    @offers = current_user.bids.where('date_time > ?', Time.now)
  end

end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/welcomes/dashboard.html.haml
.dashboard-jobs-container
  - if current_user.poster_jobs == [] && current_user.helper_jobs == [] && current_user.bids == []
    .standard-width-content 
      %h1 Welcome!
      %h2 Get started by posting or browsing tasks and making an offer from the links above.
  -else
    .dashboard-jobs-column
      .dashboard-jobs-top
        %h2 Your Posted Tasks
        = link_to 'FIND A HELPR', new_job_path
      .dashboard-jobs-details
        - if @poster_jobs == []
          %h5 (No tasks to display)
        -else
          - @poster_jobs.order('date_time').each do |job|
            .dashboard-job
              %h3= link_to job.title, job_path(job)
              %h4= job.date_time.to_formatted_s(:long_ordinal)
              %h4= job.address
              .dashboard-job-links
                = link_to 'EDIT', edit_job_path(job), class: 'left'
                - if job.helper == nil
                  = link_to pluralize(job.applicants.count, 'offer'), job_path(job), class: 'right'
                - else
                  = link_to 'assigned', job_path(job), class: 'right'
    .dashboard-jobs-column
      .dashboard-jobs-top
        %h2 Your Pending Offers
        = link_to 'LEND A HAND', jobs_path
      .dashboard-jobs-details
        - if @offers == []
          %h5 (No offers to display)
        -else
          - @offers.order('date_time').each do |offer|
            - if offer.job.helper == nil
              .dashboard-job
                %h3= link_to offer.job.title, job_path(offer.job)
                %h4= offer.date_time.to_formatted_s(:long_ordinal)
                %h4= offer.job.address
                %p= offer.note
                .dashboard-job-links
                  = link_to 'EDIT', edit_bid_path(offer), class: 'left'
                  = link_to 'WITHDRAW', bid_path(offer), method: :delete, class: 'right'
    .dashboard-jobs-column
      .dashboard-jobs-top
        %h2 You're Helping With
        = link_to 'BROWSE POSTS', jobs_path
      .dashboard-jobs-details
        - if @helper_jobs == []
          %h5 (No tasks to display)
        -else
          - @helper_jobs.order('date_time').each do |job|
            .dashboard-offer
              %h3= link_to job.title, job_path(job)
              %h4= job.date_time.to_formatted_s(:long_ordinal)
              %h4= job.address
              %p= job.instructions

app/views/welcomes/index.html.haml
.header-image#first-header
  %h1 Helpr
.welcome-index-text
  .subheader
    %h2 Welcome to Helpr, the new way to connect people needing help with those offering it. It's safe and easy to use, and founded on a strict no-payment policy. Scroll down to learn more.
.header-image
  %h1 Community
.welcome-index-text
  .subheader
    %h3 Just enter a location and what you need on our simple form. Our community will be able to offer a hand, and when you select a Helpr we'll send them the details.
    = link_to 'FIND A HELPR', new_job_path
.header-image
  %h1 Helping
.welcome-index-text
  .subheader
    %h3 Browse our map for requests that suit you, click the volunteer button and leave a note and revised time if you'd like. If your offer is accepted, Helpr will email all the details.
    = link_to 'LEND A HAND', jobs_path
.header-image
  %h1 Sign Up
.welcome-index-text
  .subheader
    %h3 Do something good today: sign up to Helpr.
    = link_to 'JOIN US', new_user_registration_path