config/routes.rb
Rails.application.routes.draw do
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { registrations: 'registrations' }

  root 'welcomes#index'

  get '/dashboard', to: 'welcomes#dashboard'
  get '/users/:id', to: 'users#profile', as: 'profile'
  
  resources :jobs do
    resources :bids, shallow: true
  end
end

app/views/layouts/_header.html.haml
.header
  %span.nav-title= link_to 'Helpr', root_path
  %ul.nav-links
    - if user_signed_in?
      %li.nav-links-item= link_to 'DASHBOARD', dashboard_path
      %li.nav-links-item= link_to 'SEE TASKS', jobs_path
      %li.nav-links-item= link_to 'POST TASK', new_job_path
      %li.nav-links-item= link_to 'ACCOUNT', edit_user_registration_path
      %li.nav-links-item= link_to 'LOGOUT', destroy_user_session_path, :method => :delete
    - else
      %li.nav-links-item= link_to 'SEE TASKS', jobs_path
      %li.nav-links-item= link_to 'POST TASK', new_job_path
      %li.nav-links-item= link_to 'LOGIN', new_user_session_path
      %li.nav-links-item= link_to 'REGISTER', new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
%head
  = favicon_link_tag image_path('favicon.ico')
  %title Helpr
  %link{href: "//fonts.googleapis.com/css?family=Montserrat", rel: "stylesheet", type: "text/css"}
  %script{ type: "text/javascript", src: "https://maps.googleapis.com/maps/api/js?key=AIzaSyC8hKAIIWTKKpcc5qz7F7RGkD9vRugPlVE"}
  = stylesheet_link_tag    'application'
  = javascript_include_tag 'application'
  = csrf_meta_tags
%body
  = render 'layouts/header'
  .site-content
    .flash-notice= alert || notice
    = yield